package com.whx.entities;
// Generated 2018-5-3 16:19:17 by Hibernate Tools 5.1.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brief generated by hbm2java。案由。
 */
@Entity
@Table(name = "brief")
public class Brief implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(length=12)
	private String briefId;
	
	//@Column(name = "briefName", nullable = false, unique = true, length=40)
	//@Column(nullable = false, unique = true, length=40)
	@Column(nullable = false, unique = false, length=40)
	private String briefName;
	
	//@Column(name = "aliases", nullable = true, unique = false, length=40)
	@Column(length=40)
	private String aliases;
	
	@OneToMany(targetEntity = Guidecase.class, mappedBy = "brief", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private Set<Guidecase> guidecases = new HashSet<Guidecase>(0);
	
	@OneToMany(targetEntity = Caseclass.class, mappedBy = "brief", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private Set<Caseclass> caseclasses = new HashSet<Caseclass>(0);
	
	@OneToMany(targetEntity = Law.class, mappedBy = "brief", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private Set<Law> laws = new HashSet<Law>(0);
	
	@OneToMany(targetEntity = Judgepoint.class, mappedBy = "brief", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private Set<Judgepoint> judgepoints = new HashSet<Judgepoint>(0);
	
	@OneToMany(targetEntity = Doc.class, mappedBy = "brief", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private Set<Doc> docs = new HashSet<Doc>(0);

	public Brief() {
	}

	public Brief(String briefId, String briefName) {
		this.briefId = briefId;
		this.briefName = briefName;
	}

	public Brief(String briefId, String briefName, String aliases, Set<Guidecase> guidecases, Set<Caseclass> caseclasses, Set<Law> laws,
			Set<Judgepoint> judgepoints, Set<Doc> docs) {
		this.briefId = briefId;
		this.briefName = briefName;
		this.aliases = aliases;
		this.guidecases = guidecases;
		this.caseclasses = caseclasses;
		this.laws = laws;
		this.judgepoints = judgepoints;
		this.docs = docs;
	}

	public String getBriefId() {
		return this.briefId;
	}

	public void setBriefId(String briefId) {
		this.briefId = briefId;
	}

	public String getBriefName() {
		return this.briefName;
	}

	public void setBriefName(String briefName) {
		this.briefName = briefName;
	}

	public String getAliases() {
		return this.aliases;
	}

	public void setAliases(String aliases) {
		this.aliases = aliases;
	}

	public Set<Guidecase> getGuidecases() {
		return this.guidecases;
	}

	public void setGuidecases(Set<Guidecase> guidecases) {
		this.guidecases = guidecases;
	}

	public Set<Caseclass> getCaseclasses() {
		return this.caseclasses;
	}

	public void setCaseclasses(Set<Caseclass> caseclasses) {
		this.caseclasses = caseclasses;
	}

	public Set<Law> getLaws() {
		return this.laws;
	}

	public void setLaws(Set<Law> laws) {
		this.laws = laws;
	}

	public Set<Judgepoint> getJudgepoints() {
		return this.judgepoints;
	}

	public void setJudgepoints(Set<Judgepoint> judgepoints) {
		this.judgepoints = judgepoints;
	}

	public Set<Doc> getDocs() {
		return this.docs;
	}

	public void setDocs(Set<Doc> docs) {
		this.docs = docs;
	}

}
