package com.whx.entities;
// Generated 2018-5-3 16:19:17 by Hibernate Tools 5.1.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caseclass generated by hbm2java
 */
@Entity
@Table(name = "caseclass")
public class Caseclass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer classId;
	
	@ManyToOne
	@JoinColumn(name = "briefId")
	private Brief brief;
	
	@Column(name = "description", nullable = false, unique = false, length=2048)
	private String description;
	
	@Column(name = "features", nullable = true, unique = false, length=2048)
	private String features;
	
	@Column(name = "keywords", nullable = false, unique = false, length=2048)
	private String keywords;
	
	@ManyToMany(targetEntity = Article.class, fetch = FetchType.LAZY,cascade=CascadeType.ALL)    
    @JoinTable(name = "caseclass_article", joinColumns = @JoinColumn(name = "classId"), inverseJoinColumns = @JoinColumn(name = "articleId"))
	private Set<Article> articles = new HashSet<Article>(0);
	
	@OneToMany(targetEntity = Guidecase.class, mappedBy = "caseclass", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private Set<Guidecase> guidecases = new HashSet<Guidecase>(0);
	
	@OneToMany(targetEntity = Doc.class, mappedBy = "caseclass", cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	private Set<Doc> docs = new HashSet<Doc>(0);

	public Caseclass() {
	}

	public Caseclass(Brief brief, String description, String keywords) {
		this.brief = brief;
		this.description = description;
		this.keywords = keywords;
	}

	public Caseclass(Brief brief, String description, String features, String keywords, Set<Guidecase> guidecases, Set<Article> articles,
			Set<Doc> docs) {
		this.brief = brief;
		this.description = description;
		this.features = features;
		this.keywords = keywords;
		this.guidecases = guidecases;
		this.articles = articles;
		this.docs = docs;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public Brief getBrief() {
		return this.brief;
	}

	public void setBrief(Brief brief) {
		this.brief = brief;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFeatures() {
		return this.features;
	}

	public void setFeatures(String features) {
		this.features = features;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public Set<Guidecase> getGuidecases() {
		return this.guidecases;
	}

	public void setGuidecases(Set<Guidecase> guidecases) {
		this.guidecases = guidecases;
	}

	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	public Set<Doc> getDocs() {
		return this.docs;
	}

	public void setDocs(Set<Doc> docs) {
		this.docs = docs;
	}

}
