package com.whx.entities;
// Generated 2018-5-3 16:19:17 by Hibernate Tools 5.1.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Doc generated by hbm2java
 */
public class Doc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer docId;
	private Brief brief;
	private Caseclass caseclass;
	
	@ManyToOne
	@JoinColumn(name = "courtCode")
	private Court court;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="relatedDocId")
	private Doc doc;
	
	private String title;
	private String source;
	private String caseNo;
	private String category;
	private String docCategory;
	private String proceeding;
	private String judge;
	private Date judgeDate;
	private String litigant;
	private String attorney;
	private String keywords;
	private String abbrevation;
	private Byte isImportant;
	private String fullPathName;
	
	@OneToMany(targetEntity=Doc.class,cascade= CascadeType.ALL,mappedBy="doc")
	private Set<Doc> docs = new HashSet<Doc>(0);
	
	
	private Set<Judgepoint> judgepoints = new HashSet<Judgepoint>(0);
	
	@ManyToMany(targetEntity = Article.class, fetch = FetchType.LAZY,cascade=CascadeType.ALL)    
    @JoinTable(name = "doc_article", joinColumns = @JoinColumn(name = "docId"), inverseJoinColumns = @JoinColumn(name = "articleId"))
	private Set<Article> articles = new HashSet<Article>(0);
	
	private Set<Guidecase> guidecases = new HashSet<Guidecase>(0);

	public Doc() {
	}

	public Doc(Brief brief, Court court, Doc doc, String title, String caseNo, String category, String docCategory,
			String proceeding, Date judgeDate, String fullPathName) {
		this.brief = brief;
		this.court = court;
		this.doc = doc;
		this.title = title;
		this.caseNo = caseNo;
		this.category = category;
		this.docCategory = docCategory;
		this.proceeding = proceeding;
		this.judgeDate = judgeDate;
		this.fullPathName = fullPathName;
	}

	public Doc(Brief brief, Caseclass caseclass, Court court, Doc doc, String title, String source, String caseNo,
			String category, String docCategory, String proceeding, String judge, Date judgeDate, String litigant,
			String attorney, String keywords, String abbrevation, Byte isImportant, String fullPathName, Set<Doc> docs,
			Set<Judgepoint> judgepoints, Set<Article> articles, Set<Guidecase> guidecases) {
		this.brief = brief;
		this.caseclass = caseclass;
		this.court = court;
		this.doc = doc;
		this.title = title;
		this.source = source;
		this.caseNo = caseNo;
		this.category = category;
		this.docCategory = docCategory;
		this.proceeding = proceeding;
		this.judge = judge;
		this.judgeDate = judgeDate;
		this.litigant = litigant;
		this.attorney = attorney;
		this.keywords = keywords;
		this.abbrevation = abbrevation;
		this.isImportant = isImportant;
		this.fullPathName = fullPathName;
		this.docs = docs;
		this.judgepoints = judgepoints;
		this.articles = articles;
		this.guidecases = guidecases;
	}

	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	public Brief getBrief() {
		return this.brief;
	}

	public void setBrief(Brief brief) {
		this.brief = brief;
	}

	public Caseclass getCaseclass() {
		return this.caseclass;
	}

	public void setCaseclass(Caseclass caseclass) {
		this.caseclass = caseclass;
	}

	public Court getCourt() {
		return this.court;
	}

	public void setCourt(Court court) {
		this.court = court;
	}

	public Doc getDoc() {
		return this.doc;
	}

	public void setDoc(Doc doc) {
		this.doc = doc;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getCaseNo() {
		return this.caseNo;
	}

	public void setCaseNo(String caseNo) {
		this.caseNo = caseNo;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getDocCategory() {
		return this.docCategory;
	}

	public void setDocCategory(String docCategory) {
		this.docCategory = docCategory;
	}

	public String getProceeding() {
		return this.proceeding;
	}

	public void setProceeding(String proceeding) {
		this.proceeding = proceeding;
	}

	public String getJudge() {
		return this.judge;
	}

	public void setJudge(String judge) {
		this.judge = judge;
	}

	public Date getJudgeDate() {
		return this.judgeDate;
	}

	public void setJudgeDate(Date judgeDate) {
		this.judgeDate = judgeDate;
	}

	public String getLitigant() {
		return this.litigant;
	}

	public void setLitigant(String litigant) {
		this.litigant = litigant;
	}

	public String getAttorney() {
		return this.attorney;
	}

	public void setAttorney(String attorney) {
		this.attorney = attorney;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getAbbrevation() {
		return this.abbrevation;
	}

	public void setAbbrevation(String abbrevation) {
		this.abbrevation = abbrevation;
	}

	public Byte getIsImportant() {
		return this.isImportant;
	}

	public void setIsImportant(Byte isImportant) {
		this.isImportant = isImportant;
	}

	public String getFullPathName() {
		return this.fullPathName;
	}

	public void setFullPathName(String fullPathName) {
		this.fullPathName = fullPathName;
	}

	public Set<Doc> getDocs() {
		return this.docs;
	}

	public void setDocs(Set<Doc> docs) {
		this.docs = docs;
	}

	public Set<Judgepoint> getJudgepoints() {
		return this.judgepoints;
	}

	public void setJudgepoints(Set<Judgepoint> judgepoints) {
		this.judgepoints = judgepoints;
	}

	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	public Set<Guidecase> getGuidecases() {
		return this.guidecases;
	}

	public void setGuidecases(Set<Guidecase> guidecases) {
		this.guidecases = guidecases;
	}

}
