package com.whx.entities;
// Generated 2018-5-3 16:19:17 by Hibernate Tools 5.1.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

/**
 * Guidecase generated by hbm2java
 */
public class Guidecase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String guideCaseNo;
	private Brief brief;
	private Caseclass caseclass;
	private Doc doc;
	private String title;
	private String source;
	private Date pubDate;
	private String category;
	private String keywords;
	private String abbrevation;
	private String fullPathName;
	
	@ManyToMany(targetEntity = Article.class, fetch = FetchType.LAZY,cascade=CascadeType.ALL)    
    @JoinTable(name = "guidecase_article", joinColumns = @JoinColumn(name = "guideCaseNo"), inverseJoinColumns = @JoinColumn(name = "articleId"))
	private Set<Article> articles = new HashSet<Article>(0);

	public Guidecase() {
	}

	public Guidecase(String guideCaseNo, Brief brief, String title, String source, Date pubDate, String category,
			String abbrevation, String fullPathName) {
		this.guideCaseNo = guideCaseNo;
		this.brief = brief;
		this.title = title;
		this.source = source;
		this.pubDate = pubDate;
		this.category = category;
		this.abbrevation = abbrevation;
		this.fullPathName = fullPathName;
	}

	public Guidecase(String guideCaseNo, Brief brief, Caseclass caseclass, Doc doc, String title, String source,
			Date pubDate, String category, String keywords, String abbrevation, String fullPathName, Set<Article> articles) {
		this.guideCaseNo = guideCaseNo;
		this.brief = brief;
		this.caseclass = caseclass;
		this.doc = doc;
		this.title = title;
		this.source = source;
		this.pubDate = pubDate;
		this.category = category;
		this.keywords = keywords;
		this.abbrevation = abbrevation;
		this.fullPathName = fullPathName;
		this.articles = articles;
	}

	public String getGuideCaseNo() {
		return this.guideCaseNo;
	}

	public void setGuideCaseNo(String guideCaseNo) {
		this.guideCaseNo = guideCaseNo;
	}

	public Brief getBrief() {
		return this.brief;
	}

	public void setBrief(Brief brief) {
		this.brief = brief;
	}

	public Caseclass getCaseclass() {
		return this.caseclass;
	}

	public void setCaseclass(Caseclass caseclass) {
		this.caseclass = caseclass;
	}

	public Doc getDoc() {
		return this.doc;
	}

	public void setDoc(Doc doc) {
		this.doc = doc;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getAbbrevation() {
		return this.abbrevation;
	}

	public void setAbbrevation(String abbrevation) {
		this.abbrevation = abbrevation;
	}

	public String getFullPathName() {
		return this.fullPathName;
	}

	public void setFullPathName(String fullPathName) {
		this.fullPathName = fullPathName;
	}

	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
