package com.whx.entities;
// Generated 2018-5-3 16:19:17 by Hibernate Tools 5.1.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Guidecase generated by hbm2java。最高人民法院发布的指导案例。
 */
@Entity
@Table(name = "guidecase")
public class Guidecase implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(length = 9)
	private String guideCaseNo;

	//@ManyToOne
	//@JoinColumn(name = "briefId", nullable = false)
	@Column(name = "brief", nullable = false, unique = false, length = 40)
	private String brief;

	@ManyToOne
	@JoinColumn(name = "classId", nullable = true, unique = false)
	private Caseclass caseclass;

	@ManyToOne
	@JoinColumn(name = "docId")
	private Doc doc;

	@Column(name = "title", nullable = false, unique = false, length = 256)
	private String title;

	@Column(name = "source", nullable = false, unique = false, length = 50)
	private String source;

	@Column(name = "pubDate", nullable = false, columnDefinition = "DATE")
	private Date pubDate;

	@Column(name = "category", nullable = false, unique = false, length = 3)
	private String category;

	@Column(name = "keywords", nullable = true, unique = false, length = 2048)
	private String keywords;

	@Column(name = "abbrevation", nullable = false, unique = false, length = 2048)
	private String abbrevation;

	@Column(name = "fullPathName", nullable = false, unique = false, length = 255)
	private String fullPathName = "E:\\myLaw\\guidecases\\";

	@ManyToMany(targetEntity = Article.class, fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "guidecase_article", joinColumns = @JoinColumn(name = "guideCaseNo"), inverseJoinColumns = @JoinColumn(name = "articleId"))
	private Set<Article> articles = new HashSet<Article>(0);

	public Guidecase() {
	}

	public Guidecase(String guideCaseNo, String brief, String title, String source, Date pubDate, String category,
			String abbrevation, String fullPathName) {
		this.guideCaseNo = guideCaseNo;
		this.brief = brief;
		this.title = title;
		this.source = source;
		this.pubDate = pubDate;
		this.category = category;
		this.abbrevation = abbrevation;
		this.fullPathName = fullPathName;
	}

	public Guidecase(String guideCaseNo, String brief, Caseclass caseclass, Doc doc, String title, String source,
			Date pubDate, String category, String keywords, String abbrevation, String fullPathName,
			Set<Article> articles) {
		this.guideCaseNo = guideCaseNo;
		this.brief = brief;
		this.caseclass = caseclass;
		this.doc = doc;
		this.title = title;
		this.source = source;
		this.pubDate = pubDate;
		this.category = category;
		this.keywords = keywords;
		this.abbrevation = abbrevation;
		this.fullPathName = fullPathName;
		this.articles = articles;
	}

	public String getGuideCaseNo() {
		return this.guideCaseNo;
	}

	public void setGuideCaseNo(String guideCaseNo) {
		this.guideCaseNo = guideCaseNo;
	}

	public String getBrief() {
		return this.brief;
	}

	public void setBrief(String brief) {
		this.brief = brief;
	}

	public Caseclass getCaseclass() {
		return this.caseclass;
	}

	public void setCaseclass(Caseclass caseclass) {
		this.caseclass = caseclass;
	}

	public Doc getDoc() {
		return this.doc;
	}

	public void setDoc(Doc doc) {
		this.doc = doc;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Date getPubDate() {
		return this.pubDate;
	}

	public void setPubDate(Date pubDate) {
		this.pubDate = pubDate;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public String getAbbrevation() {
		return this.abbrevation;
	}

	public void setAbbrevation(String abbrevation) {
		this.abbrevation = abbrevation;
	}

	public String getFullPathName() {
		return this.fullPathName;
	}

	public void setFullPathName(String fullPathName) {
		this.fullPathName = fullPathName;
	}

	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
