package com.whx.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 2018-3-18 17:04:40 by Hibernate Tools 5.1.6.Final

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(length = 60)
	private String account;// 账号

	@Column(name = "password", nullable = false, unique = false, length = 60)
	private String password;// 登录密码

	@Column(name = "category", nullable = false, unique = false, length = 7)
	private String category;// 用户类别：普通用户、律师、公检法工作人员、高校教师、其他

	@Column(name = "phone", nullable = false, unique = true, length = 13)
	private String phone;// 联系电话

	@Column(name = "email", nullable = true, unique = false, length = 45)
	private String email;// 电子信箱

	@Column(name = "concerns", nullable = true, unique = false, length = 1024)
	private String concerns;// 用户关注点

	@Column(name = "contributions", nullable = true, unique = false)
	private Short contributions;// 用户贡献的资料数量

	public User() {
	}

	public User(String account, String password, String category) {
		this.account = account;
		this.password = password;
		this.category = category;
	}

	public User(String account, String password, String category, String phone, String email, String concerns,
			Short contributions) {
		this.account = account;
		this.password = password;
		this.category = category;
		this.phone = phone;
		this.email = email;
		this.concerns = concerns;
		this.contributions = contributions;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		// String passwordMD5=common.Encrypter.md5Encrypt(password);
		this.password = password;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getConcerns() {
		return this.concerns;
	}

	public void setConcerns(String concerns) {
		this.concerns = concerns;
	}

	public Short getContributions() {
		return this.contributions;
	}

	public void setContributions(Short contributions) {
		this.contributions = contributions;
	}
}